### ISSUE TITLE
Textbox not working

### ISSUE THREAD

**Issue by BestyAU** [MaxSSD/customtk-openai#1]
Unable to get the API return to display in the textbox - from what I can tell, this isn't implemented yet? Or am I missing something?

**Comment by MaxSSD** [comment]
Hey hey I just pushed the new commit it more or less works, but I think the limitation is that customtkinter does not support textvariable in CTkTextbox so there is no scroll and parsing just yet as I used CTkEntry. The code is a very rough skeleton, please let me know if you figure it out. 

What it looks like rn:
![image](https://user-images.githubusercontent.com/86234226/215315741-55b893b1-1681-4475-9c29-66f05bb463b4.png)

**Comment by MaxSSD** [comment]
Pushed another one. I updated gui to customtkinter and added view tabs. It should work almost properly. 

I think that CTkEntry doesn't have tab parsing as CTkTextbox has, but it works properly in the answers.txt file.
